### ISSUE TITLE
CMake should complain when missing *required* dependency is not installed

### ISSUE THREAD

**Issue by romainletendart** [fundamental/rtosc#13]
Running "cmake" inside the project result in following output:

-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_FLUID_EXECUTABLE) 
-- checking for module 'ntk'
--   package 'ntk' not found
-- checking for module 'jack'
--   found jack, version 0.122.0
-- checking for module 'liblo'
--   package 'liblo' not found
-- Found PkgConfig
-- Did NOT find Liblo...
-- Found JACK...
-- Did NOT find NTK...
-- Did NOT find fltk...
-- Configuring done
-- Generating done

So, ok, it complains about not finding some packages (ntk, jack, liblo) but still complete the generation of the Makefile.

But then, when running the generated Makefile, I have errors such like:

/usr/bin/ld: cannot find -ljack

After installing libjack-dev, the compilation just ends up fine.

So, in my opinion, we should have:

pkg_check_modules(JACK REQUIRED jack)

instead of just:

pkg_check_modules(JACK jack)

inside the CMakeLists.txt. That way, we clearly see what packages are *required* and those who are not.

What do you think?

**Comment by fundamental** [comment]
Jack isn't actually required to build the minimal core which is pretty much just src/rtosc.c
Jack is required to use include/rtosc/thread-link.h, however any code using that should get disabled if jack isn't found. I'll update once I've fixed this issue.

**Comment by fundamental** [comment]
It seems to be fixed, let me know if you have any further issues.
