### ISSUE TITLE
Compilation on precise

### ISSUE THREAD

**Issue by tresf** [fundamental/rtosc#17]
Mark,

The `c++11` flag seems to break compilation on Ubuntu 12.04 Precise per [`CMakeLists.txt#L19`](https://github.com/fundamental/rtosc/blob/master/CMakeLists.txt#L19).

Changing this to `c++0x` seems to remedy this issue.

The reason I bring this up is our Travis environment over at LMMS still runs on Precise, so if we can tackle this upstream, it will help with the 2.5 integration effort. :)

**Comment by fundamental** [comment]
I recommend using a more recent compiler. That is what is done in rtosc's .travis.yml file.
