### ISSUE TITLE
Option to choose gui backend

### ISSUE THREAD

**Issue by nick87720z** [fundamental/rtosc#35]
Hello.
Not that i develop something on top of it, just wrote gentoo ebuild for it.
For now, without such switch, the only right way is to make ntk hard dependency, without ability to build with fltk, since automagical dependencies are unwanted in such distros.

**Comment by fundamental** [comment]
Thanks for taking the time to make an ebuild.

If you are making a package, you shouldn't need fltk, ntk, liblo, etc. As long as the cmake flag BUILD_RTOSC_EXAMPLES is false, the examples which depend upon fltk/ntk should not be built which eliminates the fltk/ntk requirement. Additionally the fltk/ntk examples are never installed, so they shouldn't be involved in package creation or dependency specification.
