### ISSUE TITLE
new release, please!

### ISSUE THREAD

**Issue by dvzrv** [fundamental/rtosc#38]
*whistle*

**Comment by fundamental** [comment]
Sure thing.
I'll give the headers a pass or two to clean them up.
Then I'll have to figure out where to do the announcement: LAA comes to
mind, but I'm not sure if anywhere else might be appropriate.

Tagging and incrementing the version number is trivial enough IIRC from
when I had setup the pkg-config stuff.

**Comment by dvzrv** [comment]
That sounds good! I think LAA is a good choice.

**Comment by fundamental** [comment]
To go along with the LA release day, I'm going to target April 14th with
whatever state the repo is in at that point.

**Comment by dvzrv** [comment]
*cough* release pleeeeease :-)

**Comment by fundamental** [comment]
Don't worry, it's happening, just with a bit of lag (hours) due to timezones.

**Comment by fundamental** [comment]
Done
