### ISSUE TITLE
Bad usage of strstr (compiler warning)

### ISSUE THREAD

**Issue by marcan** [fundamental/rtosc#46]
From zynaddsubfx build logs (which embed rtosc):
```
zynaddsubfx-3.0.5/rtosc/src/dispatch.c:293:16: warning: argument 2 null where non-null expected [-Wnonnull]
```

This references [this code](https://github.com/fundamental/rtosc/blob/ba5a5e38dabe0ded37e46b76a1d4c0abd5667579/src/dispatch.c#L293).

I'm not sure what the intent of the code was, or what it might actually break in practice, but `strstr(foo, NULL)` is definitely wrong.

**Comment by fundamental** [comment]
Confirmed, I've got a fix for this, but it's mixed in with a lot of other changes at the moment.

**Comment by JohannesLorenz** [comment]
@fundamental , is this still mixed with other code?
