### ISSUE TITLE
Fl_Osc_View.H: error: invalid user-defined conversion

### ISSUE THREAD

**Issue by hwpfeil** [fundamental/rtosc#51]
example/complex/Fl_Osc_View.H:175, no known conversion
from ‘Fl_Osc_View::populate(const rtosc::Ports*)::<lambda(const rtosc::Port*, const char*, void*)>’ 
to ‘rtosc::port_walker_t’ {aka ‘void (*)(const rtosc::Port*, const char*, const char*, const rtosc::Ports&, void*, void*)’}
Same issue exists in example/complex/window.cpp:156.
In ports.h,  the fifth parameter  of rtosc::walk_ports() is "port_walker_t walker".
(using -fpermissive -std=c++17)

**Comment by fundamental** [comment]
Resolved by 03d0e0e595f814aa95eb0b0c312d766a8a5aa13f
