### ISSUE TITLE
More optimal behavior for rtosc_message (possible API break)

### ISSUE THREAD

**Issue by nick87720z** [fundamental/rtosc#56]
Proposed difference is in return value for rtosc_message in case of failure.
For now if buffer is too small, it just returns zero length.
Buffer could be reallocated for bigger size, but that needs new call with NULL buffer pointer just to know required size. However, this size could be returned on actual attempt to fill buffer. No even need to null buffer automatically - if buffer is about to be reallocated, than already received data could be preserved during realloc, and remaining data could be received in addition to already received data (well, if OSC allowes).

Of if this is implemented: https://github.com/mattconte/tlsf/issues/21
then reallocation could be done without actual data movement - for case if osc doesn't support partial message pass in a way, described above.

**Comment by fundamental** [comment]
The core of rtosc by design does not perform allocations. I understand the motivation for the feature request, but I do not plan on making this modification.
