### ISSUE TITLE
Error on strdup() not available when using c++11

### ISSUE THREAD

**Issue by carlo-bramini** [fundamental/rtosc#66]
I got this error when building the code:

```
rtosc/test/path-collapse.cpp: In function ‘int main()’:
rtosc/test/path-collapse.cpp:6:16: error: ‘strdup’ was not declared in this scope; did you mean ‘strcmp’?
    6 |     char *P1 = strdup("/foo/bar/../baz");
      |                ^~~~~~
      |                strcmp
```

The problem is the `-std=c++11` option to the compiler.
If this option is set, then `strdup()` is not available.
Changing to `-std=gnu++11` fixes the issue for the compilers that support this value.

**Comment by fundamental** [comment]
To confirm (since AFAIK this doesn't impact any of my systems, nor our CI setup), adding `#include <cstring>` to the start of that test resolves this issue for you, right?

**Comment by carlo-bramini** [comment]
I tried to add `cstring` but unfortunately it did not change.

This is the content of `string.h` which declares `strdup()` function:

```
#if __MISC_VISIBLE || __POSIX_VISIBLE >= 200809 || __XSI_VISIBLE >= 4
char    *strdup (const char *) __malloc_like __result_use_check;
#endif
```

https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/include/string.h;h=32199c027ae0ba4a68884f458065287058193dd2;hb=HEAD#l83

When `-std=c++11` is used, it seems that none of those macros have the expected value for declaring `strdup()`, which are set into `sys/features.h` of the system includes:

https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/include/sys/features.h;h=45476ce4ad507575e617e86e2d7f69daee90639f;hb=HEAD

At the moment, the only solution to bypass the trouble on my side in an easy manner is to add a custom `strdup()`, which is a simple thing hopefully:

```
static char *strdup(const char *s)
{
    if (!s) return NULL;
    int len = strlen(s);
    char *p = (char *)malloc(len + 1);
    if (!p) return NULL;
    return (char *)memcpy(p, s, len + 1);
}
```

that perhaps may be enabled by doing something like an `#ifdef HAVE_STRDUP...#endif`.
I hope that you will find this report useful.

**Comment by fundamental** [comment]
This compilation issue should now be resolved.
